### ISSUE TITLE
Bug: ng add not working

### ISSUE THREAD

**Issue by dertuerke** [ngneat/transloco#16]
Hi if i try to add transloco i get this error:
`An unhandled exception occurred: Collection "@ngneat/transloco" cannot be resolved.`

Error-Log
```
[error] Error: Collection "@ngneat/transloco" cannot be resolved.
    at NodeModulesEngineHost._resolveCollectionPath (C:\Users\burak\ng-transloco\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:91:15)
    at NodeModulesEngineHost.createCollectionDescription (C:\Users\burak\ng-transloco\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (C:\Users\burak\ng-transloco\node_modules\@angular-devkit\schematics\src\engine\engine.js:147:40)
    at SchematicEngine.createCollection (C:\Users\burak\ng-transloco\node_modules\@angular-devkit\schematics\src\engine\engine.js:140:43)
    at AddCommand.getCollection (C:\Users\burak\ng-transloco\node_modules\@angular\cli\models\schematic-command.js:128:35)
    at AddCommand.runSchematic (C:\Users\burak\ng-transloco\node_modules\@angular\cli\models\schematic-command.js:291:50)
    at AddCommand.executeSchematic (C:\Users\burak\ng-transloco\node_modules\@angular\cli\commands\add-impl.js:148:31)
    at AddCommand.run (C:\Users\burak\ng-transloco\node_modules\@angular\cli\commands\add-impl.js:114:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Environment:
Angular CLI: 8.2.2
Node: 10.16.3
OS: win32 x64

**Comment by itayod** [comment]
Hi @dertuerke I thanks for open this issue, I will fix that in a moment

**Comment by itayod** [comment]
I fixed the issue and updated the package, you may install and try again it should work for you now :)

**Comment by dertuerke** [comment]
@itayod Love u 💋

**Comment by dertuerke** [comment]
@itayod i found two another bugs :)

1.) When using 'ng add', you are asked which loader to use (Http or Webpack).

If you select "Http" there, you have the possibility to choose between "JSON" and "TypeScript" in the next step. 

Is it correct that you can select "TypeScript" here? Because the loader references a ".json" file.

Http == JSON?
WebPack == Typescript?


2.) If you have selected Webpack and Typescript, then the wrong path to the file is given in the loader.

`../../assets/i18n/${langPath}`

**Comment by itayod** [comment]
Thanks!, I will take a look at this later on

**Comment by itayod** [comment]
@dertuerke Thanks again, I fixed the wrong import path.
as for the loaders, you almost right, but if you choose webpack import, you still can work with `.json` files. so it's not necessary:
 
Http == JSON?
WebPack == Typescript?

As for you'r second issue, I wasn't able to reproduce it, could you try install again the package and see if it's still happening?

**Comment by dertuerke** [comment]
@itayod ok.
But it is correct, when i choose "http" that i can choose between "json" and "Typescript"?

Path is now correct :)
