### ISSUE TITLE
SSR with transloco - "When using the default fallback, a fallback language must be provided in the config!"

### ISSUE THREAD

**Issue by RonRofe** [ngneat/transloco#263]
## Current behavior

App is kind of fully loaded, but without my transloco languages and texts.

## Expected behavior

App fully loaded with all the defined in transloco.

## Minimal reproduction of the problem with instructions

After implementing Angular Universal" on my app, running `npm run build:ssr` -> `npm run serve:ssr` and Entering the URL, the following error appears couple of times on the TERMINAL:
```
(node:95351) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
X1
```
ERROR Error: When using the default fallback, a fallback language must be provided in the config!
    at DefaultFallbackStrategy.getNextLangs (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1344407)
    at TranslocoService.handleFailure (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1354845)
    at CatchSubscriber.selector (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1349321)
    at CatchSubscriber.error (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1226637)
    at TapSubscriber._error (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/main.js:1:3416113)
    at TapSubscriber.error (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1081661)
    at RetrySubscriber._error (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1081876)
    at RetrySubscriber.error (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1081661)
    at RetrySubscriber.error (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:3403169)
    at MapSubscriber._error (/Users/USER_NAME/Desktop/FOLDER_NAME/../dist/PROJECT_NAME/server/main.js:1:1081876)
```
X10

*Notice that before SSR implementatino it was wokring well and all loaded successfully.

transloco.config.ts:

```js
module.exports = {
  defaultLang: 'heb',
  failedRetries: 2,
  prodMode: true,
  fallbackLang: ['heb', 'en'],
  reRenderOnLangChange: true,
  rootTranslationsPath: 'src/assets/i18n/',
  availableLangs: ['en', 'heb'],
};
```

## Environment

Angular version: 9.0.5
Browser: Chrome (desktop) version 80.0.3987.149
For Tooling issues: v13.12.0
Platform:  MacOS
IDE: VSC
Transloco version: `"@ngneat/transloco": "^2.13.5"`

**Comment by itayod** [comment]
@RonRofe could you show us also your `TranslocoLoader`?
