### ISSUE TITLE
ngcc build error

### ISSUE THREAD

**Issue by gkTim** [ngneat/transloco#282]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I run `ngcc` on a project with transloco I get the following error on the transloco build:

```npx ngcc --async false

Compiling @ngneat/transloco : main as umd
Error: Expected UMD module file (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/flat/index.js) to contain exactly one statement, but found 6.
    at UmdReflectionHost.computeUmdModule (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:75:23)
    at FactoryMap.factory (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:31:84)
    at FactoryMap.get (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/utils.js:93:48)
    at UmdReflectionHost.getUmdModule (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:56:36)
    at UmdReflectionHost.getModuleStatements (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:70:34)
    at UmdReflectionHost.computeExportsOfUmdModule (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:84:53)
    at FactoryMap.factory (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:32:84)
    at FactoryMap.get (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/utils.js:93:48)
    at UmdReflectionHost.getExportsOfModule (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:50:94)
    at DelegatingReflectionHost.getExportsOfModule (/Users/timingensiep/Projects/bauhaus/gus-cms/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:71:34)
```

## Expected behavior

It should run without errors.

## Minimal reproduction of the problem with instructions

Create Angular 9.1.x Project and add transloco.

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## What is the motivation / use case for changing the behavior?

To use Angular with Jest you need to run ngcc to make it work.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.16.3
- Platform:  Mac

Others:

</code></pre>

**Comment by danyo1399** [comment]
just upgraded to angular 9 and getting this too

**Comment by HitomiTenshi** [comment]
@gkTim @danyo1399 
I'm getting this error as well, though it happened for me when upgrading from Angular version `9.1.4` to `9.1.6`.

Pinning Angular to `9.1.4` fixes this problem. I assume this is an error on Angular's side.

**Comment by mohamedaarab1994** [comment]
I got the same error too

**Comment by danyo1399** [comment]
wonder if the flat dependency is the only issue. it wouldnt be a big effort to remove that dependency.

**Comment by HitomiTenshi** [comment]
@mohamedaarab1994 @danyo1399
Guys... the `flat` dependency isn't the issue here. Please go to your `package.json` and pin all Angular dependencies to version `9.1.4`, it's an issue with the latest Angular compiler.

e. g.:

```json
  "dependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/animations": "9.1.4",
    "@angular/cli": "~9.1.5",
    "@angular/common": "9.1.4",
    "@angular/compiler": "9.1.4",
    "@angular/compiler-cli": "9.1.4",
    "@angular/core": "9.1.4",
    "@angular/forms": "9.1.4",
    "@angular/language-service": "9.1.4",
    "@angular/platform-browser": "9.1.4",
    "@angular/platform-browser-dynamic": "9.1.4",
    "@angular/router": "9.1.4",
  }
```

Remove any `^` or `~` signs and set it to version `9.1.4`, then run `npm install`.

If for some reason `npm install` doesn't work, try removing the `node_modules` folder and then running `npm install` again.

That fixed it for me, version `9.1.6` has some compiler issue.

**Comment by krokofant** [comment]
9.1.7 seems to work for me

**Comment by krokofant** [comment]
@giorgi0203 Since you're specifying your version with `~` you will get later version than `9.1.4`. Read the previous comments, you need to pin them.

**Comment by HitomiTenshi** [comment]
Can someone create an Angular issue that informs them of their breaking compiler change? I'm too lazy to do that 😄 

They changed something since version `9.1.5` that breaks existing libraries that were supported until `9.1.4` like what happened with this one.

**Comment by itayod** [comment]
I am closing this issue since it seems to be Angular compiler's issue, for those who still have any difficulties I suggest you open an Issue in Angular's repository.

**Comment by shaharkazaz** [comment]
@krokofant you placed the wrong link 🙂

**Comment by krokofant** [comment]
@shaharkazaz 🤦‍♂️

https://github.com/angular/angular/issues/37508
