### ISSUE TITLE
Error: NullInjectorError: No provider for InjectionToken DEFAULT_LOCALE!

### ISSUE THREAD

**Issue by YazaWainakh** [ngneat/transloco#315]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am trying to set up an Angular 2 project with i18n. Followed the tutorial [here](https://lokalise.com/blog/angular-localization-with-transloco/) using Transloco and all works great. However, when I run the unit tests I get this error, and I cant find anything online to help me solve it. Any help would be really appreciated. 

    Chrome 84.0.4147.89 (Linux x86_64) AppComponent should render title FAILED
        NullInjectorError: R3InjectorError(DynamicTestModule)[TranslocoLocaleService -> InjectionToken DEFAULT_LOCALE -> InjectionToken DEFAULT_LOCALE]: 
          NullInjectorError: No provider for InjectionToken DEFAULT_LOCALE!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TranslocoLocaleService', 'InjectionToken DEFAULT_LOCALE', 'InjectionToken DEFAULT_LOCALE' ] })
            at <Jasmine>
            at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:914:1)
            at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11059:1)
            at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11059:1)
            at injectInjectorOnly (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:800:1)
            at Module.ɵɵinject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:804:1)
            at Object.TranslocoLocaleService_Factory [as factory] (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:972:212)
            at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11226:1)
            at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11048:1)
            at NgModuleRef$1.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:23933:1)
            at Object.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22198:1)
           Chrome 84.0.4147.89 (Linux x86_64): Executed 1 of 3 (1 FAILED) (0 secs / 0.12 secs)
           Chrome 84.0.4147.89 (Linux x86_64) AppComponent should render title FAILED

Here is my app.component.spec.ts file:

      import { TestBed, async } from '@angular/core/testing'
      import { RouterTestingModule } from '@angular/router/testing'
      import { AppComponent } from './app.component'
      import { TranslocoLocaleModule, LOCALE_LANG_MAPPING } from '@ngneat/transloco-locale'

      export function getTranslocoModule(config: Partial<TranslocoConfig> = {}) {
         return TranslocoTestingModule.withLangs(
        { en, de },
        {
          availableLangs: ['en', 'de'],
          defaultLang: 'en',
          fallbackLang: 'de',
          reRenderOnLangChange: true,
          ...config
        });
    }
    
    describe('AppComponent', () => {
        beforeEach(async(() => {
          TestBed.configureTestingModule({
            imports: [
              getTranslocoModule(),
              RouterTestingModule,
              TranslocoLocaleModule
            ],
            declarations: [
              AppComponent
            ],
            providers: [
            {
              provide: LOCALE_LANG_MAPPING,
              useValue: undefined
            }]
          }).compileComponents();
        }));
    
      it('should render title', () => {
        const fixture = TestBed.createComponent(AppComponent)
        fixture.detectChanges()
        const compiled = fixture.nativeElement
        expect(compiled.querySelector('.content span').textContent).toContain('pricetracer app is running!')
      })

     xit('should create the app', () => {
          const fixture = TestBed.createComponent(AppComponent)
          const app = fixture.componentInstance
          expect(app).toBeTruthy()
    })

     xit(`should have as title 'pricetracer'`, () => {
         const fixture = TestBed.createComponent(AppComponent)
         const app = fixture.componentInstance
         expect(app.title).toEqual('pricetracer')
     })
    })

## Minimal reproduction of the problem with instructions
app.module.ts

<pre><code>
import { BrowserModule } from '@angular/platform-browser'
import { NgModule } from '@angular/core'

import { AppRoutingModule } from './app-routing.module'
import { AppComponent } from './app.component'
import { HttpClientModule } from '@angular/common/http'
import { TranslocoRootModule } from './transloco-root.module'
import { TranslocoLocaleModule } from '@ngneat/transloco-locale'

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    TranslocoRootModule,
    TranslocoLocaleModule.init({
      defaultLocale: 'en-US',
      langToLocaleMapping: {
        en: 'en-US',
        de: 'de-DE'
      }
    }),
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
</code></pre>

## Environment

<pre><code>
Angular version: 10.0.1

Browser:
- [ x] Chrome (desktop) version 84.0.4147.89
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.16.3
- Platform:  Fedora 31

Others:

</code></pre>

**Comment by YazaWainakh** [comment]
It seems that in transloco-locale.config.d.ts there are a number of declarations that needs to be added as providers in app.component.spec.ts Testbed, they include (LOCALE_LANG_MAPPING, LOCALE_DEFAULT_LOCALE, LOCALE_CURRENCY_MAPPING, LOCALE_CONFIG, TRANSLOCO_NUMBER_TRANSFORMER, TRANSLOCO_DATE_TRANSFORMER). That solved this error.

**Comment by YazaWainakh** [comment]
However, when adding the providers, I dont know the value or the class to be used. Here is my test bed so far.
```
beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [getTranslocoModule(), RouterTestingModule, TranslocoLocaleModule],
      declarations: [AppComponent],
      providers: [
        {
          provide: LOCALE_LANG_MAPPING,
          useValue: <<??>>
        },
        {
          provide: LOCALE_DEFAULT_LOCALE,
          useValue: <<??>>
        },
        {
          provide: LOCALE_CONFIG,
          useValue: <<??>>
        },
        {
          provide: LOCALE_CURRENCY_MAPPING,
          useValue: <<??>>
        },
        {
          provide: TRANSLOCO_DATE_TRANSFORMER,
          useClass: DefaultDateTransformer
        },
        {
          provide: TRANSLOCO_NUMBER_TRANSFORMER,
          useClass: DefaultNumberTransformer
        },
      ]
    }).compileComponents()
  }))
```

**Comment by YazaWainakh** [comment]
That's how I solved the problem.
```
describe('AppComponent', () => {
  beforeEach(async(() => {
    /**
     * Transloco Locale configuration constants
     * For more configuration options go to https://netbasal.gitbook.io/transloco/plugins/locale-l10n#configuration-options
     */
    const globalFormatConfig = {
      date: {
        dateStyle: 'long',
        timeStyle: 'long',
      },
    }

    const deDEFormatConfig = {
      date: {
        timeStyle: 'medium',
      },
      currency: {
        minimumFractionDigits: 0,
      },
    }

    const localeConfig = {
      global: globalFormatConfig,
      localeBased: {
        'de-DE': deDEFormatConfig,
      },
    }

    const langToLocaleMapping = {
      en: 'en-US',
      de: 'de-DE',
    }

    const defaultLocale = {
      en: 'en-US',
    }

    const localeToCurrencyMapping = {
      en: 'USD',
      de: 'EUR',
    }

    TestBed.configureTestingModule({
      imports: [getTranslocoModule(), RouterTestingModule, TranslocoLocaleModule],
      declarations: [AppComponent],
      providers: [
        {
          provide: LOCALE_LANG_MAPPING,
          useValue: langToLocaleMapping,
        },
        {
          provide: LOCALE_DEFAULT_LOCALE,
          useValue: defaultLocale,
        },
        {
          provide: LOCALE_CONFIG,
          useValue: localeConfig,
        },
        {
          provide: LOCALE_CURRENCY_MAPPING,
          useValue: localeToCurrencyMapping,
        },
        {
          provide: TRANSLOCO_DATE_TRANSFORMER,
          useClass: DefaultDateTransformer,
        },
        {
          provide: TRANSLOCO_NUMBER_TRANSFORMER,
          useClass: DefaultNumberTransformer,
        },
      ],
    }).compileComponents()
  }))
```
