### ISSUE TITLE
TypeError: Invalid option : timeStyle

### ISSUE THREAD

**Issue by YazaWainakh** [ngneat/transloco#338]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
This problem didn't show up before, but recently I keep getting this error.

```
Chrome Headless 85.0.4183.83 (Linux x86_64) AppComponent should render title FAILED
	TypeError: Invalid option : timeStyle
	    at <Jasmine>
	    at localizeDate (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:46:1)
	    at DefaultDateTransformer.transform (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:834:1)
	    at TranslocoLocaleService.localizeDate (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:922:1)
	    at TranslocoDatePipe.transform (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:1158:1)
	    at ɵɵpipeBind2 (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:24429:1)
	    at AppComponent_Template (ng:///AppComponent.js:202:38)
	    at executeTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:7329:1)
	    at refreshView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:7198:1)
	    at refreshComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8335:1)
Chrome Headless 85.0.4183.83 (Linux x86_64): Executed 2 of 11 (1 FAILED) (0 secs / 0.097 secs)
Chrome Headless 85.0.4183.83 (Linux x86_64) AppComponent should render title FAILED
	TypeError: Invalid option : timeStyle
	    at <Jasmine>
	    at localizeDate (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:46:1)
	    at DefaultDateTransformer.transform (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:834:1)
	    at TranslocoLocaleService.localizeDate (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:922:1)
	    at TranslocoDatePipe.transform (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco-locale/__ivy_ngcc__/fesm2015/ngneat-transloco-locale.js:1158:1)
	    at ɵɵpipeBind2 (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:24429:1)
	    at AppComponent_Template (ng:///AppComponent.js:202:38)
	    at executeTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:7329:1)
	    at refreshView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:7198:1)
	    at refreshComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:8335:1)
```
This is the part where `timeStyle` is used in the test suite, if I remove those two lines then everything works fine.

```
beforeEach(() => {
    const globalFormatConfig = {
      date: {
        dateStyle: 'long',
         timeStyle: 'long',        <-- here
      },
    }

    const deDEFormatConfig = {
      date: {
        timeStyle: 'medium',      <-- and here
      },
      currency: {
        minimumFractionDigits: 0,
      },
    }

    const localeConfig = {
      global: globalFormatConfig,
      localeBased: {
        'de-DE': deDEFormatConfig,
      },
    }

    const langToLocaleMapping = {
      en: 'en-US',
      de: 'de-DE',
    }

    const defaultLocale = {
      en: 'en-US',
    }

    const localeToCurrencyMapping = {
      en: 'USD',
      de: 'EUR',
    }

    TestBed.configureTestingModule({
      imports: [getTranslocoTestingModule(), RouterTestingModule, TranslocoLocaleModule, HttpClientModule],
      declarations: [AppComponent, LanguagePickerComponent],
      providers: [
        provideMockStore({ initialState }),
        {
          provide: LOCALE_LANG_MAPPING,
          useValue: langToLocaleMapping,
        },
        {
          provide: LOCALE_DEFAULT_LOCALE,
          useValue: defaultLocale,
        },
        {
          provide: LOCALE_CONFIG,
          useValue: localeConfig,
        },
        {
          provide: LOCALE_CURRENCY_MAPPING,
          useValue: localeToCurrencyMapping,
        },
        {
          provide: TRANSLOCO_DATE_TRANSFORMER,
          useClass: DefaultDateTransformer,
        },
        {
          provide: TRANSLOCO_NUMBER_TRANSFORMER,
          useClass: DefaultNumberTransformer,
        },
      ],
    }).compileComponents()

    mockStore = TestBed.inject(MockStore)
  })
```

If I write 
`<span>
  {{ date | translocoDate: { dateStyle: 'medium', timeStyle: 'medium' } }}
</span>`

I get console errors:
```
TypeError: can't set option timeStyle in Date.toLocaleDateString()
    localizeDate ngneat-transloco-locale.js:46
    transform ngneat-transloco-locale.js:834
    localizeDate ngneat-transloco-locale.js:922
    transform ngneat-transloco-locale.js:1158
    pipeBind2 Angular
    AppComponent_Template app.component.html:23
```

## Environment

<pre><code>
Angular version: 10.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 80.0 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.16.3  
- Platform:  Fedora 31

</code></pre>

**Comment by itayod** [comment]
Hi @YazaWainakh which version of transloco-locale do you use?

**Comment by YazaWainakh** [comment]
Hi,
    "@ngneat/transloco": "^2.18.3",
    "@ngneat/transloco-locale": "^1.3.1",

**Comment by itayod** [comment]
could you try update to 1.33 and try again?

**Comment by YazaWainakh** [comment]
Everything works perfect now. Thank you :)
