### ISSUE TITLE
Dependency "flat" is missing in "@ngneat/transloco-locale"

### ISSUE THREAD

**Issue by muuvmuuv** [ngneat/transloco#402]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am trying to switch over to pnpm but cannot fully install the application because `@ngneat/transloco`, `@ngneat/transloco-keys-manager` and `@ngneat/transloco-optimize` are missing the dependency `flat`. I have seen it added to the root package.json which may work in the workspace environment but not if installed through pnpm. npm works, but I guess it's because its more verbose.

```
An error occurred during the build:
Error: The target entry-point "@ngneat/transloco-locale" has missing dependencies:
 - flat

    at TargetedEntryPointFinder.findEntryPoints (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40:23)
    at /Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:28:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:28:29)
    at /Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@angular/compiler-cli@11.2.0_76e9c380e6ad5966e08dbe567ecd27ed/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@ngtools/webpack@11.2.0_3daa3c457009f35fea0191938f28fc89/node_modules/@ngtools/webpack/src/ngcc_processor.js:163:16)
    at /Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@ngtools/webpack@11.2.0_3daa3c457009f35fea0191938f28fc89/node_modules/@ngtools/webpack/src/ivy/host.js:55:18
    at /Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@ngtools/webpack@11.2.0_3daa3c457009f35fea0191938f28fc89/node_modules/@ngtools/webpack/src/ivy/host.js:47:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/@ngtools/webpack@11.2.0_3daa3c457009f35fea0191938f28fc89/node_modules/@ngtools/webpack/src/ivy/host.js:45:32)
    at actualResolveModuleNamesWorker (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/typescript@4.1.5/node_modules/typescript/lib/typescript.js:105298:133)
    at resolveModuleNamesWorker (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/typescript@4.1.5/node_modules/typescript/lib/typescript.js:105536:26)
    at resolveModuleNamesReusingOldState (/Users/marvin/Development/M8FINDER/APP/node_modules/.pnpm/typescript@4.1.5/node_modules/typescript/lib/typescript.js:105650:24)
An unhandled exception occurred: The target entry-point "@ngneat/transloco-locale" has missing dependencies:
 - flat

See "/private/var/folders/p8/v45460fx40sdsqvz89vhmwr80000gn/T/ng-hqAcp9/angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.

❯ pnpm why flat
Legend: production dependency, optional only, dev only

dependencies:
@ngneat/transloco 2.20.0
└── flat 5.0.2

devDependencies:
@ngneat/transloco-keys-manager 2.7.1
└── flat 5.0.2
@ngneat/transloco-optimize 1.0.2
└── flat 4.1.1%
```

## Expected behavior

`flat` installed in each package to avoid missing dependency errors.

## Minimal reproduction of the problem with instructions

Install through pnpm

## What is the motivation / use case for changing the behavior?

Cannot use pnpm with ngneat packages.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kerosin** [comment]
Ran into the same problem with `pnpm`

Workaround was to manually add `flat` as devDependency to the *package.json*
```"flat": "5.0.2",```

**Comment by shaharkazaz** [comment]
@muuvmuuv I'm not sure what's the issue here with `pnpm` 🤔 
Looking at the error logged it's saying that `@ngneat/transloco-locale` is missing `flat` but he doesn't even need that package as a dependency.  

If you look at [`@ngneat/transloco`](https://github.com/ngneat/transloco/blob/master/projects/ngneat/transloco/package.json#L45), [`@ngneat/transloco-keys-manager`](https://github.com/ngneat/transloco-keys-manager/blob/master/package.json#L86) and [`@ngneat/transloco-optimize`](https://github.com/ngneat/transloco/blob/master/projects/ngneat/transloco-optimize/package.json#L27) all have `flat` as a dependency.

Am I missing something?

**Comment by muuvmuuv** [comment]
@shaharkazaz but `@ngneat/transloco-locale` does not.

**Comment by shaharkazaz** [comment]
@muuvmuuv `@ngneat/transloco-locale` doesn't need to since he doesn't depend on `flat,` feel free to correct me if you see otherwise. (I searched the lib for usages just to be sure but didn't find anything)

**Comment by muuvmuuv** [comment]
Noticed that too. I wonder why Angular things it depends on it.

**Comment by shaharkazaz** [comment]
@muuvmuuv if we agree that `@ngneat/transloco-locale` doesn't depend on `flat` but `pnpm` is failing on that, I don't think this is a Transloco related issue.

**Comment by muuvmuuv** [comment]
It's Angular that produces the error not pnpm, I just used pnpm as my package manager. I could not find the usage of flat in locale either. I am still investigating but maybe Angular does some weird node module resolution here.

**Comment by muuvmuuv** [comment]
As a temporary fix its possible to install flat by hand or install with hoist option: `pnpm i --shamefully-hoist`

**Comment by shaharkazaz** [comment]
@muuvmuuv I'm closing this issue since, as I understand, it's not really related to the lib.
Please feel free to reopen if you come to another conclusion 👍
