### ISSUE TITLE
Bug(scope): Build failed

### ISSUE THREAD

**Issue by JakaRua** [ngneat/transloco#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

Errors occur when starting the build

`npm run transloco:build && ng serve --configuration=demo`

```
    node_modules/@ngneat/transloco/lib/transloco.interceptor.d.ts:12:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
    
    12     static ɵfac: i0.ɵɵFactoryDeclaration<DefaultInterceptor, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/@ngneat/transloco/lib/transloco.interceptor.d.ts:13:22 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.
    
    13     static ɵprov: i0.ɵɵInjectableDeclaration<DefaultInterceptor>;
                            ~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@ngneat/transloco/lib/transloco-fallback-strategy.d.ts:12:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
    
    12     static ɵfac: i0.ɵɵFactoryDeclaration<DefaultFallbackStrategy, never>;

```

```
ERROR in ./node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs 1457:30-52
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs 1382:23-45
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs 1456:30-52
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)

ERROR in ./node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs 1338:22-40
Can't import the named export 'ɵɵngDeclarePipe' from non EcmaScript module (only default export is available)


```

### Expected behavior

Successful build

### Please provide a link to a minimal reproduction of the bug

haven`t

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.0.0
Angular: 10.0.8
Node: 12.14.1
Package Manager: 6.13.4
OS: win32 x64 (Windows 11)
```

### I would like to make a pull request for this bug

No

**Comment by JakaRua** [comment]
Ok, thank you. But you can add this information somewhere on the site. Because I understood that the problem is in the version, I could not find this information anywhere. For some versions of the angular use the version of the plugin. I will be grateful

**Comment by JakaRua** [comment]
Sorry, but I have another problem with 3.2.0
```
An unhandled exception occurred: Collection "node_modules\\@ngneat\\transloco\\schematics\\src\\collection.json" cannot be resolved.
See "\AppData\Local\Temp\ng-zVAbl9\angular-errors.log" for further details.
```

```
[error] Error: Collection "\node_modules\\@ngneat\\transloco\\schematics\\src\\collection.json" cannot be resolved.
    at NodeModulesEngineHost.resolve (node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:75:19)
    at NodeModulesEngineHost.resolve (node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:55:35)
    at NodeModulesEngineHost._resolveCollectionPath (node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:80:37)
    at NodeModulesEngineHost.createCollectionDescription (node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:110:27)
    at SchematicEngine._createCollectionDescription (node_modules\@angular-devkit\schematics\src\engine\engine.js:148:40)
    at SchematicEngine.createCollection (node_modules\@angular-devkit\schematics\src\engine\engine.js:141:43)
    at GenerateCommand.getCollection (node_modules\@angular\cli\models\schematic-command.js:128:35)
    at GenerateCommand.initialize (node_modules\@angular\cli\models\schematic-command.js:44:37)
    at async GenerateCommand.initialize (node_modules\@angular\cli\commands\generate-impl.js:13:9)
    at async GenerateCommand.validateAndRun (node_modules\@angular\cli\models\command.js:125:9)
```

**Comment by JakaRua** [comment]
And on version 3.2.0 the same problem ((
```
node_modules/@ngneat/transloco/lib/loader-component.component.d.ts:5:21 - error TS2694: Namespace '"node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

5     static ɵcmp: i0.ɵɵComponentDeclaration<TranslocoLoaderComponent, "ng-component", never, { "html": "html"; }, {}, never, never>;
                      ~~~~~~~~~~~~~~~~~~~~~~
node_modules/@ngneat/transloco/lib/transloco.module.d.ts:27:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

27     static ɵfac: i0.ɵɵFactoryDeclaration<TranslocoModule, never>;
```

**Comment by JakaRua** [comment]
Yes, 2.35.5 working, but on this version not work transloco build

`ng generate @ngneat/transloco:join --default-Lang en --translation-path ./src/translation --out-dir ./src/assets/i18n`

response 
`Nothing to be done.`

On version 3.0.0 build working

**Comment by shaharkazaz** [comment]
@JakaRua I'm closing this issue since this version is no longer supported.
You are welcome to search the repo for past issues in this area, the code at that version, or consult the community.
The upgrade to Angular 12 from Angular 10 should be pretty smooth and easy. I recommend upgrading so you can use v3+.

**Comment by JakaRua** [comment]
Ok, i understand, thx.

**Comment by shaharkazaz** [comment]
@JakaRua I've added a [compatibility table](https://ngneat.github.io/transloco/docs/getting-started/installation#angular--transloco-versions), thanks for the input 👍
