### ISSUE TITLE
Bug(scope): TranslocoTestingModule -> Cannot read properties of undefined (reading 'toPromise')

### ISSUE THREAD

**Issue by Hypenate** [ngneat/transloco#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

When following [this guide](https://ngneat.github.io/transloco/docs/unit-testing/), the compiler throws a runtime error when running the tests:

> Cannot read properties of undefined (reading 'toPromise')
> TypeError: Cannot read properties of undefined (reading 'toPromise')
>     at C:\git\Grizzly\node_modules\@ngneat\transloco\fesm2015\ngneat-transloco.mjs:1418:73
>     at Array.map (<anonymous>)
>     at Array.preloadAllLangs (C:\git\Grizzly\node_modules\@ngneat\transloco\fesm2015\ngneat-transloco.mjs:1418:42)

### Expected behavior

When all languages are provided, it should succeed.

### Please provide a link to a minimal reproduction of the bug

/

### Please provide the environment you discovered this bug in

```markdown
Transloco: 
Angular: 15
Node: 16
Package Manager: yarn
OS: Windows 1
```

### Browser

```markdown
Chrome
```

### Additional context

The code:

**transloco-testing.module.ts**
```
import type { ModuleWithProviders } from '@angular/core';
import type { TranslocoTestingOptions } from '@ngneat/transloco';
import { TranslocoTestingModule } from '@ngneat/transloco';
import en from '../../../../../../apps/foo/portal/src/assets/i18n/en.json';

export const getTranslocoModule = (options: TranslocoTestingOptions = {}): ModuleWithProviders<TranslocoTestingModule> => {
  return TranslocoTestingModule.forRoot({
    langs: { en },
    translocoConfig: {
      availableLangs: ['en'],
      defaultLang: 'en',
    },
    preloadLangs: true,
    ...options,
  });
};
```
foo.spec.ts
```
describe('Save Success Interceptor', () => {
  let spectator: SpectatorHttp<FooSaveSuccessInterceptorService>;
  const createHttp = createHttpFactory({
    imports: [getTranslocoModule()],
    service: FooSaveSuccessInterceptorService,
    mocks: [ToastrService, TranslocoService],
  });

  const defaultToastrSettings = {
    closeButton: true,
    easeTime: 250,
    progressBar: true,
    timeOut: 1000,
    toastClass: 'foo-toastr ngx-toastr ',
  };

  beforeEach(() => {
    spectator = createHttp();
  });

  it('should not intercept in case of a 200', (done) => {
    const mockHandler = {
      handle: jest.fn(() =>
        of(
          new HttpResponse({
            status: 200,
          })
        )
      ),
    };

    const toastrService = spectator.inject(ToastrService);
    const toastrServiceSpy = jest.spyOn(toastrService, 'success');

    spectator.service.intercept(new HttpRequest<unknown>(HttpMethod.GET, '/thing', {}), mockHandler).subscribe(
      (response) => {
        expect(response).toBeTruthy();
        done();
      },
      (err: unknown) => {
        fail(err);
      }
    );

    expect(toastrServiceSpy).toBeCalledTimes(0);
  });
}
```

All tests fails because of this issue.
Maybe I forgot something?

### I would like to make a pull request for this bug

No

**Comment by mlz11** [comment]
I have the same problem. @Hypenate have you found a solution since ?

**Comment by vmillet-dev** [comment]
Hello, did you solve this issue ? If so, how ? I'm also stuck

**Comment by brianpooe** [comment]
@Hypenate did you manage to resolve this issue?

**Comment by Hypenate** [comment]
Sorry for the (very) late responses.
No, did not fix it.
